export const FETCH_MAINTENANCE_REQUEST = "FETCH_MAINTENANCE_REQUEST";
export const FETCH_MAINTENANCE_SUCCESS = "FETCH_MAINTENANCE_SUCCESS";
export const FETCH_MAINTENANCE_FAILURE = "FETCH_MAINTENANCE_FAILURE";

export const CREATE_MAINTENANCE_REQUEST = "CREATE_MAINTENANCE_REQUEST";
export const CREATE_MAINTENANCE_SUCCESS = "CREATE_MAINTENANCE_SUCCESS";
export const CREATE_MAINTENANCE_FAILURE = "CREATE_MAINTENANCE_FAILURE";

export const UPDATE_MAINTENANCE_REQUEST = "UPDATE_MAINTENANCE_REQUEST";
export const UPDATE_MAINTENANCE_SUCCESS = "UPDATE_MAINTENANCE_SUCCESS";
export const UPDATE_MAINTENANCE_FAILURE = "UPDATE_MAINTENANCE_FAILURE";